name: cengkeh
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.1 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.10+1
  flutter_svg_provider: ^1.0.7
  visibility_detector: ^0.4.0+2
  get: ^4.7.2
  flutter: 
    sdk: flutter
  youtube_player_flutter: ^9.1.1
  styled_widget: ^0.4.1
  video_player: ^2.9.2
  marquee_list: ^1.0.0
  flutter_animate: ^4.5.0
  shared_preferences: ^2.1.0
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.1.0
  webview_flutter_wkwebview: ^3.16.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  image_picker: ^1.1.2
  url_launcher: ^6.1.15
  chewie: ^1.5.0 
  wakelock_plus: ^1.2.8
  keyboard_avoider: ^0.2.0
  flutter_file_dialog: ^3.0.2
  file_selector: ^1.0.3
  logger: ^2.5.0
  logging: ^1.0.2
  firebase_messaging: ^15.1.6
  avatars: ^3.0.2
  flutter_vector_icons: ^2.0.0
  fl_chart: ^0.66.2


 

dev_dependencies: 
  flutter_lints: ^5.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/cengkeh.png

  


 