name: Build Flutter Android APK and Upload to GitHub Releases

on:
  push:
    branches:
      - gh-pages  # Ganti sesuai branch utama kamu, misalnya 'main' jika pakai 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable

    - name: Cache Flutter and Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.pub-cache
          ~/.gradle
        key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-flutter

    - name: Install dependencies (with retry)
      run: |
        for i in 1 2 3; do flutter pub get && break || sleep 10; done

    - name: Build APK
      run: flutter build apk --release

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        body: APK built automatically from GitHub Actions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
